# -*- coding: utf-8 -*-
from pathlib import Path
import cpuinfo
import sys
import json
import pandas as pd
import joblib
import numpy as np
import time

# Ensemble of three trained models
base_dir = Path(__file__).resolve().parent
model_dir = base_dir / "model"
out_dir = base_dir / "results_csv"
out_dir.mkdir(parents=True, exist_ok=True)

# Compatibility: models saved when fix_suspicious_numeric lived in __main__
if str(model_dir) not in sys.path:
    sys.path.insert(0, str(model_dir))
try:
    __import__("feature_utils")
except Exception as e:
    print("Error", e)

model_paths = [
    model_dir / "new_CatBoost.pkl",
    model_dir / "new_LogisticRegression.pkl",
    model_dir / "new_GradientBoosting.pkl",
]

models = []
for i in range(len(model_paths)):
    if not model_paths[i].exists():
        print(f"[Warn] missing model: {model_paths[i]}")
        continue
    models.append(joblib.load(model_paths[i]))


# Convert numpy types to native Python types for JSON 
def to_py(obj):
    if not obj:
        return obj
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, dict):
        return {k: to_py(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [to_py(v) for v in obj]
    return obj


def predict(raw_df: pd.DataFrame, debug: bool = False) -> dict:
    X_raw = raw_df.copy()
    probs = []
    calc_start = time.time()

    for i in range(len(model_paths)):
        prob_pos = None
        if hasattr(models[i], "predict_proba"):
            proba = models[i].predict_proba(X_raw)[0]
            prob_pos = float(proba[1]) if len(proba) >= 2 else float(proba[0])
            probs.append(prob_pos)

    if not probs:
        print("[Error] no models loaded")
        return

    final_prob = float(sum(probs) / len(probs)) if probs else None
    if final_prob is not None:
        final_prob = round(final_prob, 2)
    risk_text = None
    if final_prob is not None:
        risk_text = "高風險" if final_prob >= 0.4 else "低風險"

    feature_map = raw_df.iloc[0].to_dict()

    if debug:
        features_used_values = {
            "Age": float(feature_map.get("Age", 0)),
            "MaxHR": float(feature_map.get("MaxHR", 0)),
            "Oldpeak": float(feature_map.get("Oldpeak", 0)),
            "Sex": str(feature_map.get("Sex", "")),
            "ExerciseAngina": str(feature_map.get("ExerciseAngina", "")),
            "ST slope": str(feature_map.get("ST_Slope", "")),
            "ChestPainType": str(feature_map.get("ChestPainType", "")),
            "RestingECG": str(feature_map.get("RestingECG", "")),
        }
    else:
        features_used_values = None

    out_dict = {
        "features_used_values": to_py(features_used_values),
        "ensemble": {
            "final_prob": to_py(final_prob),
            "risk_text": risk_text,
        }
    }

    calc_time = time.time() - calc_start
    CALC_TIME_CSV = out_dir / "prediction_time.csv"
    info = cpuinfo.get_cpu_info()
    if not CALC_TIME_CSV.exists():
        with open(CALC_TIME_CSV, "w") as f:
            f.write("cpu,calc_time_seconds,date\n")
    with open(CALC_TIME_CSV, "a") as f:
        f.write(f"{info['brand_raw']} {info['arch']} {info['hz_advertised_friendly']},{calc_time},{time.strftime('%Y-%m-%d %H:%M:%S')}\n")
    return out_dict


def main():
    input_csv = base_dir / "results_csv" / "model_input_features.csv"
    out_json = out_dir / "prediction_ensemble.json"

    # Read model input generated by collect_features.py
    if not input_csv.exists():
        print(f"[Error] missing input: {input_csv}")
        return

    raw_df = pd.read_csv(input_csv)
    if raw_df.empty:
        print("[Error] model_input_features.csv is empty")
        return

    out_dict = predict(raw_df, True)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(out_dict, f, ensure_ascii=False, indent=2)
    print("\n[Done] predictions saved:")
    print(f"  {out_json}")

if __name__ == "__main__":
    main()
